# Copyright (c) Microsoft. All rights reserved.

"""Generic supervisor agent factory for multi-agent workflows."""

from typing import Any

from agent_framework import BaseChatClient, ChatAgent

from spec_to_agents.models.messages import SupervisorDecision

__all__ = ["create_supervisor_agent"]


def create_supervisor_agent(
    client: BaseChatClient,
    participants_description: str,
    supervisor_name: str = "Supervisor",
    **kwargs: Any,
) -> ChatAgent:
    """
    Create generic supervisor agent for multi-agent workflow orchestration.

    IMPORTANT: This factory is GENERIC and reusable for any multi-agent workflow.
    It is NOT specific to event planning.

    This function is typically called internally by SupervisorWorkflowBuilder,
    which automatically extracts participant descriptions from agent properties.

    Parameters
    ----------
    client : BaseChatClient
        Chat client for creating the agent (injected by SupervisorWorkflowBuilder)
    participants_description : str
        Description block listing all available participants with their IDs and roles.
        This is automatically generated by SupervisorWorkflowBuilder from agent properties.
        Format:
        "Available participants:

        - **participant_id_1** (ParticipantName): Description of participant 1's role
        - **participant_id_2** (ParticipantName): Description of participant 2's role
        ..."
    supervisor_name : str
        Name for the supervisor agent (default: "Supervisor")
    **kwargs : Any
        Additional keyword arguments for client.create_agent()

    Returns
    -------
    ChatAgent
        Supervisor agent with SupervisorDecision structured output

    Examples
    --------
    Typically called by SupervisorWorkflowBuilder:
    >>> # Builder automatically extracts participant descriptions
    >>> supervisor_agent = create_supervisor_agent(
    ...     client=client,
    ...     participants_description=builder._extract_descriptions(),
    ...     supervisor_name="Event Planning Supervisor",
    ... )

    Manual usage (if needed):
    >>> participants_desc = '''Available participants:
    ... - **venue** (Venue Specialist): Finds suitable event venues
    ... - **budget** (Budget Analyst): Analyzes event costs
    ... '''
    >>> supervisor_agent = create_supervisor_agent(
    ...     client=client,
    ...     participants_description=participants_desc,
    ...     supervisor_name="Event Planning Supervisor",
    ... )
    """
    instructions = SUPERVISOR_SYSTEM_PROMPT_TEMPLATE.format(
        supervisor_name=supervisor_name,
        participants_description=participants_description,
    )

    # Supervisor does not need tools for routing decisions
    # Tools can be added via kwargs if needed for specific workflows
    return client.create_agent(
        name=supervisor_name,
        instructions=instructions,
        response_format=SupervisorDecision,
        tools=None,
        store=True,  # Use service-managed thread for global context
        **kwargs,
    )


SUPERVISOR_SYSTEM_PROMPT_TEMPLATE = """
You are the {supervisor_name}, responsible for orchestrating a team of specialist agents to fulfill the user's request.

# Available Participants

{participants_description}

# Your Responsibilities

1. **Route intelligently**: Analyze the conversation history and current state to determine which
   participant should contribute next
2. **Maintain global context**: You see the entire conversation; participants see only their
   local history
3. **Avoid redundancy**: Don't route to a participant if they've already provided sufficient
   information
4. **Request clarification**: If the user's request is ambiguous or you need additional context,
   ask the user directly
5. **Know when to finish**: When all necessary information has been gathered, synthesize the
   final result

# Routing Strategy

Apply these general principles when deciding which participant to route to next:

- **Start with foundation**: Route to participants that gather foundational information
  (requirements, constraints) before those that build upon it
- **Consider dependencies**: If one participant's work depends on another's output, route in
  dependency order
- **Maximize parallelism**: When multiple participants can work independently, you may route to
  them in any order
- **Skip unnecessary work**: Don't route to a participant whose expertise isn't needed for the
  current request
- **Iterate when needed**: Return to participants if their earlier output needs refinement based
  on new information or user feedback
- **Balance thoroughness and efficiency**: Gather sufficient information without unnecessary
  redundancy

# Decision Format

Respond with SupervisorDecision structured output:

- **next_agent**:
  - Participant ID (e.g., 'venue', 'budget') to route to next
  - `null` when ready to synthesize final result

- **user_input_needed**:
  - `true` if you need user clarification before proceeding
  - `false` otherwise

- **user_prompt**:
  - Question for the user (required if user_input_needed=true)
  - `null` otherwise

**Workflow completion signal**: Set `next_agent=null` AND `user_input_needed=false` when all
necessary work is complete and you're ready to provide the final synthesized result.
"""
